Repository maglnet/ComposerRequireChecker, pull requests merged in 2019-11, with the labels that each got.

#159 change update interval to monthly
  .dependabot/config.yml
Labels: dependencies, enhancement

#161 Require ext-zend-opcache for development.
  composer.json
Labels: bug

#165 Test that CheckCommand finds unknown symbols.
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
Labels: enhancement
