Repository maglnet/ComposerRequireChecker, pull requests merged in 2020-11, with the labels that each got.

#210 Add doctrine/conding-standard as phpcs rule
  .github/workflows/coding-standard.yml
  .gitignore
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  phpcs.xml.dist
  src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php
  src/ComposerRequireChecker/Cli/Application.php
  src/ComposerRequireChecker/Cli/CheckCommand.php
  src/ComposerRequireChecker/Cli/Options.php
  src/ComposerRequireChecker/DefinedExtensionsResolver/DefinedExtensionsResolver.php
  src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php
  src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensions.php
  src/ComposerRequireChecker/DependencyGuesser/DependencyGuesser.php
  src/ComposerRequireChecker/DependencyGuesser/GuessFromLoadedExtensions.php
  src/ComposerRequireChecker/DependencyGuesser/Guesser.php
  src/ComposerRequireChecker/DependencyGuesser/GuesserInterface.php
  src/ComposerRequireChecker/Exception/DependenciesNotInstalled.php
  src/ComposerRequireChecker/Exception/DependenciesNotInstalledException.php
  src/ComposerRequireChecker/Exception/InvalidInputFile.php
  src/ComposerRequireChecker/Exception/InvalidInputFileException.php
  src/ComposerRequireChecker/Exception/InvalidJson.php
  src/ComposerRequireChecker/Exception/InvalidJsonException.php
  src/ComposerRequireChecker/Exception/NotReadable.php
  src/ComposerRequireChecker/Exception/NotReadableException.php
  src/ComposerRequireChecker/Exception/UnknownExtension.php
  src/ComposerRequireChecker/Exception/UnknownExtensionException.php
  src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php
  src/ComposerRequireChecker/FileLocator/LocateFilesByGlobPattern.php
  src/ComposerRequireChecker/GeneratorUtil/ComposeGenerators.php
  src/ComposerRequireChecker/JsonLoader.php
  src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
  src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php
  src/ComposerRequireChecker/UsedSymbolsLocator/LocateUsedSymbolsFromASTRoots.php
  test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php
  test/ComposerRequireCheckerTest/BinaryTest.php
  test/ComposerRequireCheckerTest/Cli/ApplicationTest.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/Cli/OptionsTest.php
  test/ComposerRequireCheckerTest/DefinedExtensionsResolver/DefinedExtensionsResolverTest.php
  test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRootsTest.php
  test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromExtensionsTest.php
  test/ComposerRequireCheckerTest/DependencyGuesser/DependencyGuesserTest.php
  test/ComposerRequireCheckerTest/FileLocator/LocateAllFilesByExtensionTest.php
  test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageDirectDependenciesSourceFilesTest.php
  test/ComposerRequireCheckerTest/FileLocator/LocateComposerPackageSourceFilesTest.php
  test/ComposerRequireCheckerTest/FileLocator/LocateFilesByGlobPatternTest.php
  test/ComposerRequireCheckerTest/JsonLoaderTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorFunctionalTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorFunctionalTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
  test/ComposerRequireCheckerTest/UsedSymbolsLocator/LocateUsedSymbolsFromASTRootsTest.php
Labels: bc break, dependencies, enhancement, help wanted

#219 Do not parse passed file if it is not a regular file
  src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php
  test/ComposerRequireCheckerTest/ASTLocator/LocateASTFromFilesTest.php
Labels: enhancement

#222 Add description how to customize the config file
  README.md
Labels: enhancement

#224 Explain the indirect dependency thingy
  README.md
Labels: enhancement

#218 Add "Composer\InstalledVersions" in symbol whitelist
  src/ComposerRequireChecker/Cli/CheckCommand.php
  src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromComposerRuntimeApi.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromComposerRuntimeApiTest.php
  test/fixtures/noUnknownComposerSymbol/composer.json
  test/fixtures/noUnknownComposerSymbol/src/SomeClass.php
  test/fixtures/noUnknownComposerSymbol/vendor/composer/installed.json
  test/fixtures/unknownComposerSymbol/composer.json
  test/fixtures/unknownComposerSymbol/src/SomeClass.php
  test/fixtures/unknownComposerSymbol/vendor/composer/installed.json
Labels: enhancement

#206 Psalm patrol
  baseline.xml
  composer.json
  composer.lock
  psalm.xml
  src/ComposerRequireChecker/Cli/Application.php
  src/ComposerRequireChecker/Cli/CheckCommand.php
  src/ComposerRequireChecker/Cli/Options.php
  src/ComposerRequireChecker/DefinedExtensionsResolver/DefinedExtensionsResolver.php
  src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromComposerRuntimeApi.php
  src/ComposerRequireChecker/DependencyGuesser/DependencyGuesser.php
  src/ComposerRequireChecker/DependencyGuesser/GuessFromLoadedExtensions.php
  src/ComposerRequireChecker/DependencyGuesser/Guesser.php
  src/ComposerRequireChecker/FileLocator/LocateAllFilesByExtension.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php
  src/ComposerRequireChecker/JsonLoader.php
  src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
  src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/DefinedSymbolsLocator/LocateDefinedSymbolsFromComposerRuntimeApiTest.php
  test/ComposerRequireCheckerTest/JsonLoaderTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
  test/fixtures/validJsonNotAnArray.json
Labels: bc break, enhancement

#223 Test automatic phar creation process
  .github/workflows/phar-creation.yml
Labels: enhancement

#226 Bump vimeo/psalm from 3.18.2 to 4.2.1
  baseline.xml
  composer.json
  composer.lock
Labels: dependencies, enhancement
