Repository maglnet/ComposerRequireChecker, pull requests merged in 2021-12, with the labels that each got.

#326 Add workflow file for automating the merges of PR opened by @dependabot.
  .github/workflows/merge-dependabot-upgrades.yml
Labels: enhancement

#327 Add support for PHP 8.1 "never" type
  data/config.dist.json
  src/ComposerRequireChecker/Cli/Options.php
Labels: enhancement

#328 Add PHP 8.1 to test matrix
  .github/workflows/phpunit.yml
Labels: enhancement, dependencies

#329 Supporting PHP 8.1 enums
  src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/DefinedSymbolCollectorTest.php
  test/fixtures/noUnknownEnumSymbols/composer.json
  test/fixtures/noUnknownEnumSymbols/src/SomeClass.php
  test/fixtures/noUnknownEnumSymbols/src/SomeEnum.php
  test/fixtures/noUnknownEnumSymbols/vendor/composer/installed.json
Labels: enhancement

#331 Add `--output=json` and `--output=text` option to CLI, to allow for better automation/reporting based on `STDOUT`
  src/ComposerRequireChecker/Cli/CheckCommand.php
  src/ComposerRequireChecker/Cli/ResultsWriter/CliJson.php
  src/ComposerRequireChecker/Cli/ResultsWriter/CliText.php
  src/ComposerRequireChecker/Cli/ResultsWriter/ResultsWriter.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/Cli/ResultsWriter/CliJsonTest.php
  test/ComposerRequireCheckerTest/Cli/ResultsWriter/CliTextTest.php
Labels: enhancement

#334 Add mutation tests to pipeline
  .github/workflows/infection.yml
  baseline.xml
  composer.json
  composer.lock
  infection.json.dist
  phpunit.xml.dist
  src/ComposerRequireChecker/Cli/ApplicationHeaderWriter.php
  src/ComposerRequireChecker/Cli/CheckCommand.php
  src/ComposerRequireChecker/Cli/Options.php
  src/ComposerRequireChecker/DefinedExtensionsResolver/DefinedExtensionsResolver.php
  src/ComposerRequireChecker/DefinedSymbolsLocator/LocateDefinedSymbolsFromASTRoots.php
  src/ComposerRequireChecker/Exception/FileParseFailed.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageDirectDependenciesSourceFiles.php
  src/ComposerRequireChecker/FileLocator/LocateComposerPackageSourceFiles.php
  src/ComposerRequireChecker/JsonLoader.php
  src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
  src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php
  test/ComposerRequireCheckerTest/Cli/ApplicationHeaderWriterTest.php
  test/ComposerRequireCheckerTest/Cli/ApplicationTest.php
  test/ComposerRequireCheckerTest/Cli/CheckCommandTest.php
  test/ComposerRequireCheckerTest/Cli/OptionsTest.php
  test/ComposerRequireCheckerTest/Cli/ResultsWriter/CliTextTest.php
  test/ComposerRequireCheckerTest/Exception/FileParseFailedTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
Labels: enhancement

#340 Drop PHP 7.4
  .github/workflows/coding-standard.yml
  .github/workflows/infection.yml
  .github/workflows/phar-creation.yml
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  .github/workflows/require-checker.yml
  README.md
  composer.json
  composer.lock
  src/ComposerRequireChecker/NodeVisitor/DefinedSymbolCollector.php
Labels: enhancement

#321 Collect class property types as "used symbols"
  src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorFunctionalTest.php
  test/ComposerRequireCheckerTest/NodeVisitor/UsedSymbolCollectorTest.php
Labels: enhancement, bc break

#339 Bump psalm to v4.15
  composer.json
  composer.lock
Labels: enhancement, dependencies

#336 Allow Symfony 6
  composer.json
  composer.lock
Labels: enhancement, dependencies

#343 Composer > Define allowed plugins (#1464)
  composer.json
Labels: enhancement, dependencies
